#spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
#spring.datasource.username=postgres
#spring.datasource.password=Chandan@2003


spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update



#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=${PORT:8080}

# Enable Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

aws.s3.bucket-name=chandan-s3bucket-12

jwt.secret=inventory-management-super-secret-key-256-bit!!
jwt.expiration=3600000


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis