#spring.datasource.url=${INVENTORY_MANAGEMENT_DATASOURCE_URL_LOCAL}
#spring.datasource.username=${INVENTORY_MANAGEMENT_DATASOURCE_USERNAME_LOCAL}
#spring.datasource.password=${INVENTORY_MANAGEMENT_DATASOURCE_PASSWORD_LOCAL}

spring.datasource.url=${INVENTORY_MANAGEMENT_DATASOURCE_URL}
spring.datasource.username=${INVENTORY_MANAGEMENT_DATASOURCE_USERNAME}
spring.datasource.password=${INVENTORY_MANAGEMENT_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update


#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=${PORT:8080}

# Enable Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

aws.s3.bucket-name=chandan-s3bucket-12

jwt.secret=${INVENTORY_MANAGEMENT_JWT_SECRET}
jwt.expiration=3600000


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

spring.security.oauth2.client.registration.google.client-id=${INVENTORY_MANAGEMENT_OAUTH2_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${INVENTORY_MANAGEMENT_OAUTH2_GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.provider.google.authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account


spring.mail.host=${INVENTORY_MANAGEMENT_MAIL_HOST}
spring.mail.port=${INVENTORY_MANAGEMENT_MAIL_PORT}
spring.mail.username=${INVENTORY_MANAGEMENT_MAIL_USERNAME}
spring.mail.password=${GOOGLE_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true